[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino

monitor_speed = 115200
upload_speed = 1500000

lib_deps =
    m5stack/M5Unified @ ^0.2.0

[env:m5stack-atoms3-ota]
platform = espressif32
board = m5stack-atoms3
framework = arduino

monitor_speed = 115200
upload_protocol = espota
upload_port = atom-saf-logger.local
; upload_port = 192.168.x.x  ; IPアドレスを直接指定する場合はこちら

lib_deps =
    m5stack/M5Unified @ ^0.2.0
