[platformio]
default_envs = m5stack-atoms3-ota

[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino

monitor_speed = 115200
upload_speed = 1500000
build_flags = -I../src

lib_deps =
    m5stack/M5Unified @ ^0.2.0

[env:m5stack-atoms3-ota]
platform = espressif32
board = m5stack-atoms3
framework = arduino

monitor_speed = 115200
upload_protocol = espota
;upload_port = atom-saf-logger.local
upload_port = 10.63.180.41
build_flags = -I../src

lib_deps =
    m5stack/M5Unified @ ^0.2.0
